# Generated by Django 3.1 on 2020-11-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_covid19data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacovid19item',
            name='active_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacovid19item',
            name='case_fatality_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacovid19item',
            name='confirmed_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacovid19item',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacovid19item',
            name='dead_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacovid19item',
            name='incidence_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacovid19item',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacovid19item',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacovid19item',
            name='recovered_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
